<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>R58Win32Helper</AssemblyName>
    <RootNamespace>R58Win32Helper</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

</Project>
